### ISSUE TITLE
Laser projector doesn't use shutter command.  Need "Blank" command

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-vivitek-projector#1]
Hello!

I'm using the Vivitek DU7098Z.  I need access to the command to blank the screen.  The shutter command does not work in this model.  I have been able to telnet to the projector and issue the commands to blank and unblank the screen successfully.  They are as follows:

To Blank the screen: 
OP BLANK=1 

To Return the screen to normal:
OP BLANK=0 

If anyone would be able to add this functionality to the module I would be grateful!

Thanks in advance!

**Comment by josephdadams** [comment]
I added this

**Comment by jsnyder886** [comment]
Awesome, thanks so much!

**Comment by josephdadams** [comment]
And for the record, the shutter command sends a blank after it sends the shutter command (according to the code) so I just added a new action that only sends blank.
